
spring.data.mongodb.uri=mongodb+srv://valmartucci_db_user:Gm7S3v60fPLrB2Aa@cluster0.graax7a.mongodb.net/musicdb?retryWrites=true&w=majority
server.port=8080

logging.level.root=WARN
logging.level.com.musicplatform=INFO
logging.level.org.springframework.data.mongodb=DEBUG

server.servlet.context-path=/
spring.application.name=Music Platform Backend